export const ProviderEndpoint = Object.freeze({
  OBOOBS_RANDOM: 'http://api.oboobs.ru/boobs/0/1/random/',
  OBOOBS_BY_ID: 'http://api.oboobs.ru/boobs/get/{id}/',
  OBOOBS_MEDIA: 'http://media.oboobs.ru/{preview}',
  OBUTTS_RANDOM: 'http://api.obutts.ru/butts/0/1/random/',
  OBUTTS_BY_ID: 'http://api.obutts.ru/butts/get/{id}/',
  OBUTTS_MEDIA: 'http://media.obutts.ru/{preview}',
  PURRBOT: 'https://purrbot.site/api/img/nsfw/{category}/{format}',
  WAIFU_PICS: 'https://api.waifu.pics/nsfw/{category}',
  N_SFW: 'https://api.n-sfw.com/nsfw/{category}',
  WAIFU_IM: 'https://api.waifu.im/images',
  SEX_COM_SEARCH: 'https://www.sex.com/portal/api/gifs/search',
  SEX_COM_WATCH: 'https://www.sex.com/pin/{id}/',
  SEX_COM_CDN: 'https://imagex1.sx.cdn.live{uri}',
  NEKOS_V4: 'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags={tag}',
  NEKOBOT: 'https://nekobot.xyz/api/image?type={type}',
  PORNGIFS_MEDIA: 'https://cdn.porngifs.com/img/{id}',
  PORNGIFS_IP_MEDIA: 'https://{resolvedIP}/img/{id}',
  PORNGIFS_TV: 'https://porngifs.tv/?action=ajax&mode=async&function=get_block&block_id=list_videos_most_recent_videos&sort_by=post_date&from={page}',
  PORNPICS_BUTT_PLUG: 'https://www.pornpics.com/butt-plug/',
  HENTAI_COSPLAY_FEED: 'https://hentai-cosplay-xxx.com/search/page/{page}/',
  AHOTTIE_COSPLAY_FEED: 'https://ahottie.top/tags/Cosplay?page={page}',
});

export const SexComNiches = Object.freeze([
  'Amateur',
  'Anal',
  'Asian',
  'Big Tits',
  'Blonde',
  'Blowjob',
  'Brunette',
  'Creampie',
  'Cumshot',
  'Hardcore',
  'Latina',
  'Lesbian',
  'MILF',
  'Masturbation',
  'Threesome',
  'Ass',
  'BBW',
  'BDSM',
  'Double Penetration',
  'Ebony',
  'Female Ejaculation',
  'Fisting',
  'Footjob',
  'Gangbang',
  'Hairy',
  'Handjob',
  'Hentai',
  'Lingerie',
  'Public Sex',
  'Pussy',
  'Toys',
]);
