'use strict';
const media = require('./media');
const d = require('./discord');
const { info } = require('./logger');
const NICHES = ['Amateur','Anal','Asian','Big Tits','Blonde','Blowjob','Brunette','Creampie','Cumshot','Hardcore','Latina','Lesbian','MILF','Masturbation','Threesome','Ass','BBW','BDSM','Double Penetration','Ebony','Female Ejaculation','Fisting','Footjob','Gangbang','Hairy','Handjob','Hentai','Lingerie','Public Sex','Pussy','Toys'];
const source = (id, fields={}) => ({ id, ...fields });
const COMMANDS = {
 '4k': { desc:'Delivers a random NSFW 4k Image/GIF', title:'NSFW 4k Image', sources:[source('nekobot',{type:'4k'})] },
 anal:{desc:'Delivers a random NSFW anal Image/GIF',title:'NSFW Anal Image',style:true,anime:[source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/anal/gif'}),source('abd',{endpoint:'https://api.n-sfw.com/nsfw/anal'}),source('nekobot',{type:'hentai_anal'}),source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=anal'})],real:[source('nekobot',{type:'anal'})]},
 ass:{desc:'Delivers a random NSFW ass Image/GIF',title:'NSFW Ass Image',style:true,anime:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/ass'}),source('waifuim',{tag:'ass'}),source('nekobot',{type:'hass'})],real:[source('obutts'),source('nekobot',{type:'ass'})]},
 blowjob:{desc:'Delivers a random NSFW blowjob Image/GIF',title:'NSFW Blowjob Image',style:true,anime:[source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/blowjob/gif'}),source('waifupics',{endpoint:'https://api.waifu.pics/nsfw/blowjob'}),source('abd',{endpoint:'https://api.n-sfw.com/nsfw/blowjob'}),source('waifuim',{tag:'oral'})],real:[source('nekobot',{type:'blowjob'})]},
 boobs:{desc:'Delivers a random NSFW boobs Image/GIF',title:'NSFW Boobs Image',style:true,anime:[source('waifuim',{tag:'oppai'}),source('nekobot',{type:'hboobs'})],real:[source('oboobs'),source('nekobot',{type:'boobs'})]},
 breeding:{desc:'Delivers a random Breeding image',title:'NSFW Breeding Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/breeding'})]},
 buttplug:{desc:'Delivers a random Buttplug image',title:'NSFW Buttplug Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/buttplug'})]},
 cages:{desc:'Delivers a random Cages image',title:'NSFW Cages Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/cages'})]},
 cum:{desc:'Delivers a random cum/ejaculation GIF',title:'NSFW Cum Image',sources:[source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/cum/gif'})]},
 ecchi:{desc:'Delivers a random Ecchi image',title:'NSFW Ecchi Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/ecchi'})]},
 ero:{desc:'Delivers a random Ero image',title:'NSFW Ero Image',sources:[source('waifuim',{tag:'ero'})]},
 feet:{desc:'Delivers a random NSFW feet Image/GIF',title:'NSFW Feet Image',style:true,anime:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/feet'})],real:[source('nekobot',{type:'feet'})]},
 fuck:{desc:'Delivers a random penetrative sex GIF',title:'NSFW Fuck Image',sources:[source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/fuck/gif'})]},
 gonewild:{desc:'Delivers a random NSFW gonewild Image/GIF',title:'NSFW Gonewild Image',sources:[source('nekobot',{type:'gonewild'})]},
 hentai:{desc:'Delivers a random NSFW hentai Image/GIF',title:'NSFW Hentai Image',sources:[source('waifuim',{tag:'hentai'}),source('nekobot',{type:'hentai'})]},
 kitsune:{desc:'Delivers a random NSFW kitsune Image/GIF',title:'NSFW Kitsune Image',sources:[source('nekobot',{type:'hkitsune'})]},
 legs:{desc:'Delivers a random Legs image',title:'NSFW Legs Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/legs'})]},
 maid:{desc:'Delivers a random Maid image',title:'NSFW Maid Image',sources:[source('waifuim',{tag:'maid'}),source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=maid'})]},
 midriff:{desc:'Delivers a random NSFW midriff Image/GIF',title:'NSFW Midriff Image',sources:[source('nekobot',{type:'hmidriff'})]},
 milf:{desc:'Delivers a random Milf image',title:'NSFW Milf Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/milf'})]},
 neko:{desc:'Delivers a random NSFW neko Image/GIF',title:'NSFW Neko Image',sources:[source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/neko/gif'}),source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/neko/img'}),source('waifupics',{endpoint:'https://api.waifu.pics/nsfw/neko'}),source('abd',{endpoint:'https://api.n-sfw.com/nsfw/neko'}),source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=catgirl'}),source('nekobot',{type:'lewdneko'})]},
 paizuri:{desc:'Delivers a random NSFW paizuri Image/GIF',title:'NSFW Paizuri Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/paizuri'}),source('waifuim',{tag:'paizuri'}),source('nekobot',{type:'paizuri'})]},
 petgirls:{desc:'Delivers a random Petgirls image',title:'NSFW Petgirls Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/petgirls'})]},
 pussy:{desc:'Delivers a random NSFW pussy Image/GIF',title:'NSFW Pussy Image',sources:[source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=pussy'}),source('nekobot',{type:'pussy'})]},
 pussylick:{desc:'Delivers a random cunnilingus GIF',title:'NSFW Pussylick Image',sources:[source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/pussylick/gif'})]},
 selfie:{desc:'Delivers a random Selfie image',title:'NSFW Selfie Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/selfie'})]},
 smothering:{desc:'Delivers a random Smothering image',title:'NSFW Smothering Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/smothering'})]},
 socks:{desc:'Delivers a random Socks image',title:'NSFW Socks Image',sources:[source('abd',{endpoint:'https://api.n-sfw.com/nsfw/socks'})]},
 tentacle:{desc:'Delivers a random NSFW tentacle Image/GIF',title:'NSFW Tentacle Image',sources:[source('nekobot',{type:'tentacle'})]},
 thigh:{desc:'Delivers a random NSFW thigh Image/GIF',title:'NSFW Thigh Image',style:true,anime:[source('nekobot',{type:'hthigh'})],real:[source('nekobot',{type:'thigh'})]},
 uniform:{desc:'Delivers a random Uniform image',title:'NSFW Uniform Image',sources:[source('waifuim',{tag:'uniform'})]},
 waifu:{desc:'Delivers a random Waifu image',title:'NSFW Waifu Image',sources:[source('waifupics',{endpoint:'https://api.waifu.pics/nsfw/waifu'}),source('waifuim',{tag:'waifu'})]},
 yuri:{desc:'Delivers a random NSFW yuri Image/GIF',title:'NSFW Yuri Image',sources:[source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/yuri/gif'}),source('abd',{endpoint:'https://api.n-sfw.com/nsfw/yuri'}),source('nekobot',{type:'hyuri'}),source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=yuri'})]}
};
function pick(arr){return arr[Math.floor(Math.random()*arr.length)];}
function poolFor(cfg, style){ if(!cfg.style) return cfg.sources; if(style==='Anime') return cfg.anime; if(style==='Real') return cfg.real; return [...cfg.anime,...cfg.real]; }
async function fetchSource(s){ info(`Selected API Source: ${JSON.stringify(s)}`); if(s.id==='purrbot') return media.fetchPurrbot(s.endpoint); if(s.id==='abd') return media.fetchABD(s.endpoint); if(s.id==='waifupics') return media.fetchWaifu(s.endpoint); if(s.id==='waifuim') return media.fetchWaifuIm(s.tag,true); if(s.id==='oboobs') return media.fetchBoobs(); if(s.id==='obutts') return media.fetchAss(); if(s.id==='nekobot') return media.fetchNekoBot(s.type); if(s.id==='nekosv4') return media.fetchNekosV4(s.endpoint); return null; }
async function runMedia(name, interaction, update=false, saved=null){ await d.defer(interaction, update); const cfg=COMMANDS[name]; const style=saved || d.getOption(interaction,'style'); let pool=poolFor(cfg,style).filter(s=>process.env.WAIFU_PICS!=='false'||s.id!=='waifupics'); if(!pool.length) pool=poolFor(cfg,style); const data=await fetchSource(pick(pool)); if(!data||data.error) return d.edit(interaction,{embeds:[{title:'❌ ▸ Error',description:data?.error==='TIMEOUT'?'API Timeout: The request took longer than 15 seconds to fulfill. Please try again later.':'Failed to fetch image.',color:0xff0000}],components:[]}); const custom=style?`refresh_${name}_${style}`:`refresh_${name}`; return d.edit(interaction,{embeds:[d.embed({title:`🔞 ▸ ${cfg.title}`,image:data.url,user:interaction.member?.user||interaction.user})],components:d.buttons(custom,data.url)}); }
async function runGif(interaction, update=false){ await d.defer(interaction, update); const n=Math.floor(Math.random()*4); let data, link; if(n===0){ data=await media.fetchSexcom(pick(NICHES)); link=data?.id?`https://www.sex.com/pin/${data.id}/`:data?.url; } else if(n===1){ data=await media.fetchPorngifs(); link=data?.url; } else if(n===2){ data=await media.fetchNekoBot('pgif'); link=data?.url; } else { data=await media.fetchPorngifsTv(); link=data?.url; } if(!data||data.error) return d.edit(interaction,{embeds:[{title:'❌ ▸ Error',description:'Failed to fetch image.',color:0xff0000}],components:[]}); return d.edit(interaction,{embeds:[d.embed({title:'🔞 ▸ NSFW GIF',image:data.url,user:interaction.member?.user||interaction.user})],components:d.buttons('refresh_gif',link||data.url)}); }
async function runSolo(interaction, update=false, saved=null){ await d.defer(interaction, update); const type=saved||d.getOption(interaction,'type'); const sources= type==='male' ? [source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/solo_male/gif'})] : type==='female' ? [source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/solo/gif'}),source('abd',{endpoint:'https://api.n-sfw.com/nsfw/masturbation'}),source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=masturbating'})] : [source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/solo/gif'}),source('abd',{endpoint:'https://api.n-sfw.com/nsfw/masturbation'}),source('purrbot',{endpoint:'https://purrbot.site/api/img/nsfw/solo_male/gif'}),source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=masturbating'})]; const data=await fetchSource(pick(sources)); if(!data||data.error) return d.edit(interaction,{embeds:[{title:'❌ ▸ Error',description:'Failed to fetch image.',color:0xff0000}],components:[]}); return d.edit(interaction,{embeds:[d.embed({title:'🔞 ▸ NSFW Solo Image',image:data.url,user:interaction.member?.user||interaction.user})],components:d.buttons(`refresh_solo_${type||'random'}`,data.url)}); }
async function runThreesome(interaction, update=false, saved=null){ await d.defer(interaction, update); const chosen=saved||d.getOption(interaction,'type'); const type=chosen||pick(['fff','ffm','mmf','nekosv4']); const src=type==='nekosv4'?source('nekosv4',{endpoint:'https://api.nekosapi.com/v4/images/random?limit=1&rating=explicit,suggestive&tags=threesome'}):source('purrbot',{endpoint:`https://purrbot.site/api/img/nsfw/threesome_${type}/gif`}); const data=await fetchSource(src); if(!data||data.error) return d.edit(interaction,{embeds:[{title:'❌ ▸ Error',description:'Failed to fetch image.',color:0xff0000}],components:[]}); return d.edit(interaction,{embeds:[d.embed({title:'🔞 ▸ NSFW Threesome Image',image:data.url,user:interaction.member?.user||interaction.user})],components:d.buttons(`refresh_threesome_${chosen||'random'}`,data.url)}); }
async function runUtility(name, interaction){ if(name==='ping') return d.callback(interaction,d.CALLBACK.CHANNEL_MESSAGE_WITH_SOURCE,{embeds:[{title:'🏓 ▸ Pong',description:`Gateway and REST bot is online. Uptime: ${Math.round(process.uptime())}s`,color:d.randomColor()}]}); if(name==='invite'){ const url=`https://discord.com/oauth2/authorize?client_id=${process.env.CLIENT_ID}&scope=bot%20applications.commands&permissions=2147485696`; return d.callback(interaction,d.CALLBACK.CHANNEL_MESSAGE_WITH_SOURCE,{embeds:[{title:'🔗 ▸ Invite',description:`[Add this bot to your server](${url})`,color:d.randomColor()}]}); } if(name==='help') return d.callback(interaction,d.CALLBACK.CHANNEL_MESSAGE_WITH_SOURCE,{embeds:[{title:'📖 ▸ Command Directory',description:Object.keys({...COMMANDS,gif:1,solo:1,threesome:1}).sort().map(c=>`\`/${c}\``).join(' • '),color:d.randomColor()}]}); }
function definitions(){ const defs=Object.entries(COMMANDS).map(([name,c])=>({name,description:c.desc,type:1,nsfw:true,integration_types:[0,1],contexts:[0,1,2],options:c.style?[{type:d.OPTION.STRING,name:'style',description:'Select the style (Anime or Real)',required:false,choices:[{name:'Anime',value:'Anime'},{name:'Real',value:'Real'}]}]:[]})); defs.push({name:'gif',description:'Delivers a random NSFW GIF',type:1,nsfw:true,integration_types:[0,1],contexts:[0,1,2]},{name:'solo',description:'Delivers a random solo masturbation Image/GIF',type:1,nsfw:true,integration_types:[0,1],contexts:[0,1,2],options:[{type:d.OPTION.STRING,name:'type',description:'Solo type',required:false,choices:[{name:'Female',value:'female'},{name:'Male',value:'male'}]}]},{name:'threesome',description:'Delivers a random threesome GIF',type:1,nsfw:true,integration_types:[0,1],contexts:[0,1,2],options:[{type:d.OPTION.STRING,name:'type',description:'The type of threesome',required:false,choices:[{name:'3 Females',value:'fff'},{name:'2 Females 1 Male',value:'ffm'},{name:'2 Males 1 Female',value:'mmf'}]}]},{name:'help',description:'Directory of all available commands and detailed information.',type:1,integration_types:[0,1],contexts:[0,1,2]},{name:'invite',description:'Get a dynamic invite link to add this bot to your server.',type:1,integration_types:[0,1],contexts:[0,1,2]},{name:'ping',description:'Advanced diagnostic metrics and latency check.',type:1,integration_types:[0,1],contexts:[0,1,2]}); return defs; }
async function execute(interaction){ const name=interaction.data?.name; if(COMMANDS[name]) return runMedia(name, interaction); if(name==='gif') return runGif(interaction); if(name==='solo') return runSolo(interaction); if(name==='threesome') return runThreesome(interaction); return runUtility(name, interaction); }
async function refresh(interaction){ const parts=interaction.data.custom_id.split('_'); const name=parts[1]; const saved=parts.slice(2).join('_'); if(COMMANDS[name]) return runMedia(name, interaction, true, saved&&saved!=='random'?saved:null); if(name==='gif') return runGif(interaction,true); if(name==='solo') return runSolo(interaction,true,saved&&saved!=='random'?saved:null); if(name==='threesome') return runThreesome(interaction,true,saved&&saved!=='random'?saved:null); }
module.exports={definitions,execute,refresh,COMMANDS};
