'use strict';
const https = require('https');
const dns = require('dns/promises');
const { info, warn, error } = require('./logger');
const API_TIMEOUT = 15000;
async function getJson(url, options = {}) { const c = new AbortController(); const t = setTimeout(() => c.abort(), API_TIMEOUT); try { const r = await fetch(url, { ...options, signal: c.signal }); if (!r.ok) throw new Error(`${r.status} ${r.statusText}`); return await r.json(); } finally { clearTimeout(t); } }
async function getText(url, options = {}) { const c = new AbortController(); const t = setTimeout(() => c.abort(), API_TIMEOUT); try { const r = await fetch(url, { ...options, signal: c.signal }); if (!r.ok) throw new Error(`${r.status} ${r.statusText}`); return await r.text(); } finally { clearTimeout(t); } }
async function getBuffer(url, options = {}) { const c = new AbortController(); const t = setTimeout(() => c.abort(), API_TIMEOUT); try { const r = await fetch(url, { ...options, signal: c.signal }); if (!r.ok) throw new Error(`${r.status} ${r.statusText}`); return Buffer.from(await r.arrayBuffer()); } finally { clearTimeout(t); } }
async function guarded(name, fn) { try { return await fn(); } catch (e) { if (e.name === 'AbortError') return { error: 'TIMEOUT' }; error(`Failed to fetch from ${name}: ${e.message}`); return null; } }
async function fetchBoobs(id = null) { return guarded('oboobs.ru', async () => { const ep = id !== null && !Number.isNaN(Number(id)) ? `http://api.oboobs.ru/boobs/get/${id}/` : 'http://api.oboobs.ru/boobs/0/1/random/'; const d = await getJson(ep); if (!d?.length) return null; return { id: d[0].id, url: `http://media.oboobs.ru/${d[0].preview}` }; }); }
async function fetchAss(id = null) { return guarded('obutts.ru', async () => { const ep = id !== null && !Number.isNaN(Number(id)) ? `http://api.obutts.ru/butts/get/${id}/` : 'http://api.obutts.ru/butts/0/1/random/'; const d = await getJson(ep); if (!d?.length) return null; return { id: d[0].id, url: `http://media.obutts.ru/${d[0].preview}` }; }); }
async function fetchPurrbot(endpoint) { return guarded('purrbot.site', async () => { const d = await getJson(endpoint); return d && !d.error && d.link ? { url: d.link } : null; }); }
async function fetchWaifu(endpoint) { if (process.env.WAIFU_PICS === 'false') return null; return guarded('waifu.pics', async () => { const d = await getJson(endpoint); return d?.url ? { url: d.url } : null; }); }
async function fetchABD(endpoint) { return guarded('n-sfw.com', async () => { const d = await getJson(endpoint); const target = d?.url_japan || d?.url_usa; if (!target) return null; return { url: target }; }); }
async function fetchWaifuIm(tag, isNsfw = true) { return guarded('waifu.im', async () => { const url = new URL('https://api.waifu.im/images'); url.searchParams.set('IncludedTags', tag); url.searchParams.set('IsNsfw', isNsfw ? 'True' : 'False'); const headers = { 'Accept-Version': 'v7' }; if (process.env.WAIFU_IM_KEY) headers.Authorization = `ApiKey ${process.env.WAIFU_IM_KEY}`; const d = await getJson(url, { headers }); return d?.items?.[0]?.url ? { url: d.items[0].url } : null; }); }
async function fetchNekosV4(endpoint) { return guarded('nekosapi.com', async () => { const d = await getJson(endpoint); return Array.isArray(d) && d[0]?.url ? { url: d[0].url, source: 'nekosv4' } : null; }); }
async function fetchNekoBot(type) { return guarded('nekobot.xyz', async () => { const d = await getJson(`https://nekobot.xyz/api/image?type=${encodeURIComponent(type)}`, { headers: { Authorization: '015445535454455354D6' } }); return d?.success && d?.message ? { url: d.message, source: 'nekobot' } : null; }); }
async function fetchSexcom(niche) { return guarded('sex.com', async () => { const page = Math.floor(Math.random() * 10) + 1; const url = new URL('https://www.sex.com/portal/api/gifs/search'); Object.entries({ 'sexual-orientation': 'straight', order: 'likeCount', search: niche, page, limit: 40 }).forEach(([k,v]) => url.searchParams.set(k, v)); const d = await getJson(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }); const arr = d?.data || []; if (!arr.length) return null; const item = arr[Math.floor(Math.random() * arr.length)]; let path = item.uri; if (!path) return null; if (path.endsWith('.webp')) path = path.slice(0, -5) + '.gif'; return { id: item.id, url: `https://imagex1.sx.cdn.live${path}` }; }); }
async function fetchPorngifs() { return guarded('porngifs.com', async () => { const id = Math.floor(Math.random() * 39239) + 1; return { id: String(id), url: `https://cdn.porngifs.com/img/${id}`, source: 'porngifs' }; }); }
async function fetchPorngifsTv() { return guarded('porngifs.tv', async () => { const page = Math.floor(Math.random() * 2603) + 1; const html = await getText(`https://porngifs.tv/?action=ajax&mode=async&function=get_block&block_id=list_videos_most_recent_videos&sort_by=post_date&from=${page}`, { headers: { 'X-Requested-With': 'XMLHttpRequest', 'User-Agent': 'Mozilla/5.0' } }); const matches = [...html.matchAll(/data-webp="([^"]+\.(?:webp|gif))"/g)]; if (!matches.length) return null; const url = matches[Math.floor(Math.random() * matches.length)][1]; return { id: String(page), url, source: 'porngifstv' }; }); }
module.exports = { fetchBoobs, fetchAss, fetchPurrbot, fetchWaifu, fetchABD, fetchWaifuIm, fetchSexcom, fetchPorngifs, fetchNekoBot, fetchNekosV4, fetchPorngifsTv };
